### PR TITLE
Support numpy arrays for rendering.

### PR DESCRIPTION
**Pull request by RLMarvin**

### CODE REVIEW

**Comment by IamEld3st** [comment]
From what I see vec3 is chips vector and ndarray is numpy. I would keep them separated.

**Comment by tarehart** [comment]
Yep we're seeing the same thing. I don't see a reason to duplicate the code though, they will both support index access forever. I don't like duck typing usually, but it's handy here.

**Comment by whatisaphone** [comment]
Peanut gallery chiming in. I'd keep them separated as well, it's cleaner that way. Think about something like Kotlin type narrowing, where it type checks each block with different type information. Or V8, which would JIT each block according to the type check. Those technical reasons don't apply in Python, but they all build off the general principle of having a well-typed program on every line, and that does still apply imo.

**Comment by whatisaphone** [comment]
The thing that jumps out to me more is using string comparison for the type checks. I think those should be `isinstance` calls.

**Comment by RLMarvin** [comment]
I think to use isinstance you'll have to import the type, so you'd need to have those installed.
I could just merge the two if statements into one line, or make a try except block if we care about supporting any subscriptable type that contains numbers.

**Pull request merged**
