### PR TITLE
Fix GUI preset load and relative path problems

### PR DESCRIPTION
**Pull request by ima9rd**
This fixes GUI loading to not discard preset configuration files that share the same name but are located in different directories. The GUI would correctly save the rlbot.cfg file when multiple agents were added with the same name, but the loading code would overwrite all presets loaded after the initial due to matching on preset name alone.

### CODE REVIEW

**Comment by ima9rd** [comment]
I'm guessing there exists code somewhere to correctly append the suffix for presets, but I couldn't find it (likely related to debugging for 3 hours straight to find the source of this issue)

**Comment by ima9rd** [comment]
Added in another GUI crash fix for agents outside of the default directory relative path.

**Comment by ima9rd** [comment]
More commits to fix relative path issues.

**Comment by ima9rd** [comment]
Unfortunately the base_subprocess_agent didn't fix the issue whatisaphone was experiencing. I'm going to continue to work on this.

**Comment by whatisaphone** [comment]
I can confirm this fixes #287.

**Comment by ima9rd** [comment]
Seems OK to merge now based on testing 👍

**Pull request merged**
