### PR TITLE
r and q commands for mac (and linux?)

### PR DESCRIPTION
**Pull request by naturecodevoid**
This allows mac users (and hopefully linux users) to run the q and r commands in the console. Previously, this was windows only.

### CODE REVIEW

**Comment by tarehart** [comment]
This only happens if the console has focus, I hope?

**Comment by naturecodevoid** [comment]
I didn't think of testing that, but I'd guess it only works when focusing on the terminal. I will test it soon.

**Comment by naturecodevoid** [comment]
I have tested this and it will only fire the command if the terminal window is open (at least on mac)

**Comment by tarehart** [comment]
OK sounds good. Thanks for this!

**Pull request merged**
