### PR TITLE
Add support for the Epic Games Launcher

### PR DESCRIPTION
**Pull request by VirxEC**
Please view line 212, idk what I should put there

### CODE REVIEW

**Comment by tarehart** [comment]
Looks good!

Probably something like this would work for the missing code:
```python
exe_and_args = [epic_exe_path] + ideal_args
_ = subprocess.Popen(exe_and_args)
```

**Comment by VirxEC** [comment]
Makes sense, did that

**Comment by tarehart** [comment]
Cool! Does it launch RL and start a match if you do `python runner.py` in the root directory?

I guess maybe you would need to comment out the steam code to test properly...

**Comment by VirxEC** [comment]
I tested both Steam & Epic Games, both of them work; they put 2 AlwaysTowardsBallAgent bots in a heatseeker match

**Review by tarehart — APPROVED** [review]
Thanks Virx!

**Pull request merged**
