### PR TITLE
Make RLBot work on Unix

### PR DESCRIPTION
**Pull request by martmists**

### CODE REVIEW

**Comment by tarehart** [comment]
Thanks for chipping in! Unfortunately getting RLBot to work on Unix also involves a lot of work in other parts of the code, especially the part where we inject logic into the game.

That part is not open source, and we don't have plans to attempt it in the short term since it will be extremely difficult (not sure if it's even possible), and we don't get very many Unix users.

**Comment by martmists** [comment]
Ah, understandable. If you do want to support Unix users, I'd be happy to help out. I don't have windows installed at all, so implementing this would be interesting to say the least.

**Comment by cominixo01** [comment]
Yeah, I'm in the same situation, only linux installed and I don't want to dual boot just for RLBot

**Comment by tarehart** [comment]
Closing for now since there's a lot of deeper changes needed first for Unix.

**Pull request closed without merging**
